config/routes.rb
Rvine::Application.routes.draw do

	root :to => 'vines#index'

  resources :vines do
    member do
      put :upvote
    end
  end

  match '/auth/twitter/callback', :to => 'sessions#create'

  resource :dashboard

  root :to => 'vines#index'

end

app/models/user.rb
class User < Couchbase::Model

  attribute :name
  attribute :twit_username
  attribute :avatar

  def self.find_or_create_from_auth_hash(hash)
    user = User.find_by_id(hash[:uid])
    unless user
      user = User.create!(:id => hash[:uid],
                          :name => hash[:info][:name],
                          :twit_username => hash[:info][:nickname],
                          :avatar => hash[:info][:image])
    end
    user
  end

end

app/models/vine.rb
require 'open-uri'
require 'uri'
require 'nokogiri'

class Vine < Couchbase::Model
  after_save :extract_video_url

  belongs_to :user

  attribute :title
  attribute :vine_url
  attribute :video_url

  #Voting API
  attribute :score, :default => 1

  validates_presence_of :title, :vine_url

  view :all, :limit => 10, :descending => true

  private

  def extract_video_url
    doc = Nokogiri(open(vine_url).read)
    self.video_url = doc.css("source").first["src"]
    save_without_callbacks
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate!
    if signed_in?
      return true
    else
      flash[:error] = "You aren't authorized to access this page"
      redirect_to(root_path)
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  helper_method :current_user

  def signed_in?
    !!current_user
  end
  helper_method :signed_in?
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = user.id
    flash[:success] = "Welcome to the club!"
    redirect_to dashboard_path
  end

  protected
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/vines_controller.rb
class VinesController < ApplicationController
  # GET /vines
  # GET /vines.json
  def index
    @vines = Vine.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @vines }
    end
  end

  # GET /vines/1
  # GET /vines/1.json
  def show
    @vine = Vine.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @vine }
    end
  end

  def upvote
    @vine = Vine.find(params[:id])
    @vine.score = @vine.score += 1
    @vine.save
    redirect_to @vine
  end

  # GET /vines/new
  # GET /vines/new.json
  def new
    @vine = Vine.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @vine }
    end
  end

  # GET /vines/1/edit
  def edit
    @vine = Vine.find(params[:id])
  end

  # POST /vines
  # POST /vines.json
  def create
    @vine = Vine.new(params[:vine])

    respond_to do |format|
      if @vine.save
        format.html { redirect_to @vine, notice: 'Vine was successfully created.' }
        format.json { render json: @vine, status: :created, location: @vine }
      else
        format.html { render action: "new" }
        format.json { render json: @vine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vines/1
  # PUT /vines/1.json
  def update
    @vine = Vine.find(params[:id])
    @vine.update(params[:vine])
    redirect_to @vine
  end

  def secure_update
    update(:cas => meta["cas"])
  end

  # DELETE /vines/1
  # DELETE /vines/1.json
  def destroy
    @vine = Vine.find(params[:id])
    @vine.destroy

    respond_to do |format|
      format.html { redirect_to vines_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_flash_messages
    [:error, :success, :info].map do |type|
      content_tag(:div, :class => "alert alert-#{type} row-fluid") do
        "<strong>#{type.capitalize}</strong> #{flash[type]}".html_safe
      end if flash[type].present?
    end.join.html_safe
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/vines_helper.rb
module VinesHelper
end

app/views/dashboards/show.html.haml
%section#welcome
  .page-header
    - if signed_in?
      %h1
        Hello, #{current_user.name}
      %p
        %img{:src => current_user.avatar, :alt => "Avatar"}
      %p= link_to("All vines", "/vines")
    - else
      %h1
        Hello, stranger
      %p
        = link_to("Sign in with your twitter account", "/auth/twitter")
    %p
      &nbsp;

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%ul.nav
	- if signed_in?
		%li
			= link_to 'Top 10 Vines', vines_path 
		%li
			= link_to 'New Vine', new_vine_path
		
	- else
		%li
			= link_to 'Top 10', vines_path
		%li
			= link_to 'Login', "/auth/twitter"	

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rate My Vine!
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %body
      .navbar-inverse.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield

app/views/vines/_form.html.haml
#vine_form{"data-role" => "page"}

  %div{"data-role" => "content"}
    = form_for @vine do |f|
      %div{"data-role" => "fieldcontain"}
        = f.label :title
        = f.text_field :title
      %div{"data-role" => "fieldcontain"}
        = f.label :vine_url
        = f.text_field :vine_url
      = f.submit "Submit", :data => {:theme => "a"}

app/views/vines/edit.html.haml
%h1 Editing #{@vine.title}

#vine{"data-role" => "page"}

  %div{"data-role" => "content"}
    = form_for @vine do |f|
      = hidden_field_tag :cas, @vine.meta[:cas]
      %div{"data-role" => "fieldcontain"}
        = f.label :title
        = f.text_field :title
      %div{"data-role" => "fieldcontain"}
        = f.label :vine_url
        = f.text_field :vine_url
      = f.submit "Submit", :data => {:theme => "a"}

= link_to 'Show', @vine
\|
= link_to 'Back', vines_path

app/views/vines/index.html.haml
%h1 Top Rated Vines

- @vines.each do |vine|
  %ul
    %li= link_to vine.title, vine
    %li= vine.score


%br

= link_to 'New Vine', new_vine_path

app/views/vines/new.html.haml
- if signed_in?
	%h1 New vine
	
	= render 'form'

- else
	%h4
		= link_to("You must be Logged in to Post a Vine!", "/auth/twitter")

= link_to 'Back', vines_path

app/views/vines/show.html.haml
%p#notice= notice

%h1= @vine.title

%video{:src => @vine.video_url, :autoplay => "autoplay", :loop => "loop", :muted => true}

%h3
  Video Score: #{@vine.score}

= form_tag(upvote_vine_path(@vine), :method => "put") do
  = submit_tag "Vote Up!"

\|
= link_to 'Back To Top Vines', vines_path